/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Deployment-model left-nav (Cloud / Self-Hosted / Platform / Other). Generated from the
  // Momento knowledgebase (readme/project/projection/ia/site.json via gen-sidebar.mjs); do not
  // hand-edit sidebars.site.json. Momento Cache + Valkey Operator pages are members (they show
  // this sidebar); Platform/Other are link references to areas that keep their own sidebars
  // below. Attached to /product/cache for now; site-wide attachment is the deferred step (T-0043).
  siteSidebar: require("./sidebars.site.json"),
  cacheSidebar: [
    { type: 'autogenerated', dirName: 'cache' }
  ],
  topicsSidebar: [
    { type: 'autogenerated', dirName: 'topics' }
  ],
  leaderboardSidebar: [
    { type: 'autogenerated', dirName: 'leaderboards' }
  ],
  cloudLinterSidebar: [
    { type: 'autogenerated', dirName: 'cloud-linter' }
  ],
  // Platform (cross-product concerns). Authentication / Account management / API were
  // consolidated here from the per-product trees (decision 0012 / T-0036); the old paths
  // 301-redirect in via site/redirects.ts.
  platformSidebar: [
    {
      type: "link",
      label: "Overview",
      href: "/platform"
    },
    {
      type: "link",
      label: "Available Regions",
      href: "/platform/regions"
    },
    {
      type: "category",
      label: "Authentication",
      link: { type: "doc", id: "platform/authentication/index" },
      collapsed: false,
      items: [
        { type: "doc", id: "platform/authentication/api-keys" },
        { type: "doc", id: "platform/authentication/tokens" },
        { type: "doc", id: "platform/authentication/roles-and-permissions" }
      ]
    },
    {
      type: "doc",
      label: "Account management",
      id: "platform/account-management/index"
    },
    {
      type: "doc",
      label: "API",
      id: "platform/api/index"
    },
    {
      type: "category",
      label: "Clients and SDKs",
      items: [
        {
          type: "autogenerated", dirName: "platform/sdks"
        }
      ]
    },
    {
      type: "category",
      label: "Connectivity",
      items: [
        {
          type: "autogenerated", dirName: "platform/connectivity"
        }
      ]
    },
    {
      type: 'category',
      label: 'Quotas and Limits',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'Auth',
          href: '/auth/limits'
        },
        {
          type: 'link',
          label: 'Cache',
          href: '/cache/manage/limits'
        },
        {
          type: 'link',
          label: 'Topics',
          href: '/topics/limits'
        },
        {
          type: 'link',
          label: 'Leaderboards',
          href: '/leaderboards/limits'
        }
      ]
    }
  ],
  mediastorageSidebar: [
    { type: 'autogenerated', dirName: 'media-storage' }
  ],
  functionsSidebar: [
    { type: 'autogenerated', dirName: 'functions' }
  ],
};

module.exports = sidebars;
