/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cacheSidebar: [
    {
      type: "html",
      value: "<span class='sidebar-title'>Table of Contents</span>",
    },
    { type: 'autogenerated', dirName: 'cache' }
  ],
  topicsSidebar: [
    {
      type: "html",
      value: "<span class='sidebar-title'>Table of Contents</span>",
    },
    { type: 'autogenerated', dirName: 'topics' }
  ],
  leaderboardSidebar: [
    {
      type: "html",
      value: "<span class='sidebar-title'>Table of Contents</span>",
    },
    { type: 'autogenerated', dirName: 'leaderboards' }
  ],
  storageSidebar: [
    {
      type: "html",
      value: "<span class='sidebar-title'>Table of Contents</span>",
    },
    { type: 'autogenerated', dirName: 'storage' }
  ],
  cloudLinterSidebar: [
    {
      type: "html",
      value: "<span class='sidebar-title'>Table of Contents</span>",
    },
    { type: 'autogenerated', dirName: 'cloud-linter' }],
  topLevelSidebar: [
    {
      type: "html",
      value: "<span class='sidebar-title'>Table of Contents</span>"
    },
    {
      type: "link",
      label: "Available Regions",
      href: "/regions"
    },
    {
      type: "link",
      label: "Clients and SDKs",
      href: "/sdks"
    },
    {
      type: 'category',
      label: 'Quotas and Limits',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'limits/index'
      },
      items: [
        {
          type: 'link',
          label: 'Auth',
          href: '/auth/limits'
        },
        {
          type: 'link',
          label: 'Cache',
          href: '/cache/limits'
        },
        {
          type: 'link',
          label: 'Topics',
          href: '/topics/limits'
        },
        {
          type: 'link',
          label: 'Leaderboards',
          href: '/leaderboards/limits'
        }
      ]
    }
  ]
};

module.exports = sidebars;
